/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jenadle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Hello Jenkins!");
        System.out.println("Hello again!!");
        //this is another comment
        // a comment
    }
    public String x() {
        System.out.println("we will see, how are you going");
        return "X";
    }
}
